import { Store } from './store.js';
import { FirebaseBridge } from './firebase.js';
import { MATERIAL_CATALOG, WORK_TYPES, UNITS } from './catalog.js';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const num=n=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(Number(n||0));
const date=d=>d?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(d)):'-';
const dt=d=>d?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d)):'-';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let page='dashboard', firebaseReady=false;
const role=()=>Store.currentUser()?.role;
const can=(roles)=>roles.includes(role());
const activeId=()=>Store.activeProject()?.id;

function toast(message,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('#toast-root').append(el);setTimeout(()=>el.remove(),3500)}
function badge(status){const m={approved:['ok','Disetujui'],pending:['warn','Menunggu'],rejected:['bad','Ditolak'],active:['ok','Aktif'],done:['info','Selesai'],open:['warn','Terbuka'],closed:['ok','Selesai']};const [c,t]=m[status]||['',status||'-'];return `<span class="badge ${c}">${esc(t)}</span>`}
function projectRows(collection){const p=activeId();return Store.list(collection).filter(x=>x.projectId===p)}
function byId(c,id){return Store.find(c,id)}
function matName(id){return byId('materials',id)?.name||'-'}
function userName(id){return byId('users',id)?.name||'-'}
function stockBalance(materialId){const ins=projectRows('stock').filter(x=>x.materialId===materialId&&x.status==='approved').reduce((s,x)=>s+Number(x.qty||0),0);const outs=projectRows('usage').filter(x=>x.materialId===materialId&&x.status==='approved').reduce((s,x)=>s+Number(x.qty||0),0);return ins-outs}
function weightedProgress(){const rows=projectRows('progress'); const total=rows.reduce((s,x)=>s+Number(x.weight||0),0); if(!total)return 0; return rows.reduce((s,x)=>s+Number(x.weight||0)*Math.min(100,Number(x.percent||0))/100,0)/total*100}
function today(){return new Date().toISOString().slice(0,10)}
function todayRows(c){return projectRows(c).filter(x=>String(x.date||x.createdAt||'').slice(0,10)===today())}

const NAV={
 dashboard:['⌂','Dashboard',['owner','admin','mandor']],projects:['▦','Proyek',['owner','admin']],materials:['▧','Material',['owner','admin','mandor']],stock:['⇩','Stok Masuk',['owner','admin','mandor']],usage:['⇧','Pemakaian',['owner','admin','mandor']],attendance:['✓','Absensi',['owner','admin','mandor']],progress:['◫','Progress & Target',['owner','admin','mandor']],issues:['!','Kendala',['owner','admin','mandor']],reports:['≡','Laporan Harian',['owner','admin','mandor']],approvals:['◎','Approval',['owner','admin']],rab:['Rp','RAB / Anggaran',['owner','admin']],purchases:['◈','Pembelian',['owner','admin']],suppliers:['S','Supplier',['owner','admin']],tools:['⌘','Alat & Inventaris',['owner','admin','mandor']],hse:['+','K3 / HSE',['owner','admin','mandor']],users:['♙','User',['owner','admin']],audit:['↺','Audit Log',['owner','admin']],settings:['⚙','Pengaturan',['owner']]
};

async function init(){await Store.init(); if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{}); Store.subscribe(()=>{if(Store.currentUser()) renderApp()}); const u=Store.currentUser(); if(u) renderApp(); else renderLogin();}

function renderLogin(){
 const s=Store.get().settings;
 $('#app').innerHTML=`<div class="login-shell"><div class="login-card"><section class="login-brand"><img src="./assets/logo-ayo-bangun.jpeg" alt="Ayo Bangun"><h1>${esc(s.companyName)}</h1><p>Construction Project ERP untuk pengendalian proyek, material, tenaga kerja, progress, laporan harian, approval, dan sinkronisasi lintas perangkat.</p></section><section class="login-form"><h2>Masuk ke aplikasi</h2><p>Gunakan akun Owner, Admin atau Mandor.</p><form id="login-form"><div class="field"><label>Username</label><input name="username" autocomplete="username" required placeholder="admin"></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" required placeholder="••••••"></div><button class="btn btn-primary" style="width:100%">Masuk</button></form><div class="demo-box"><strong>Login awal lokal</strong><br>Owner: <b>owner</b> / <b>AYOBANGUN#2026</b><br>Admin: <b>admin</b> / <b>0000</b><br>Mandor: <b>mandor1</b> / <b>1234</b><br><br>Setelah Firebase diaktifkan, gunakan akun Firebase yang dibuat oleh Owner/Admin.</div></section></div></div>`;
 $('#login-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const u=fd.get('username'),p=fd.get('password');try{if(Store.get().settings.firebaseConfig){await ensureFirebase();const cred=await FirebaseBridge.signIn(u,p);const profile=await FirebaseBridge.getUserProfile(cred.uid);if(!profile||profile.active===false) throw new Error('Profil user tidak aktif atau belum dibuat di Firestore');Store.setSessionUser(profile);await FirebaseBridge.bootstrap(Store.exportData());await FirebaseBridge.startRealtime({onCollection:(c,r)=>Store.applyRemoteCollection(c,r),onSettings:r=>Store.applyRemoteSettings(r),onError:er=>toast(er.message,'bad')});Store.setRemote(FirebaseBridge);}else{const local=await Store.loginLocal(u,p);if(!local) throw new Error('Username atau password salah');}page='dashboard';renderApp()}catch(err){toast(err.message||'Login gagal','bad')}};
}

function renderApp(){const user=Store.currentUser(); if(!user){renderLogin();return} const projects=Store.list('projects').filter(p=>p.status!=='archived').filter(p=>user.role!=='mandor'||!(user.projectIds||[]).length||(user.projectIds||[]).includes(p.id)); if(!Store.activeProject()&&projects[0])Store.setActiveProject(projects[0].id); const nav=Object.entries(NAV).filter(([,v])=>v[2].includes(user.role)).map(([k,v])=>`<button data-page="${k}" class="${page===k?'active':''}"><span>${v[0]}</span>${v[1]}</button>`).join(''); const p=Store.activeProject(); $('#app').innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand-row"><img src="./assets/logo-ayo-bangun.jpeg"><div><strong>Ayo Bangun.ID</strong><small>Contractor ERP</small></div></div><nav class="nav">${nav}</nav><div class="sidebar-footer"><div class="user-role">${esc(user.role)}</div><div class="user-name">${esc(user.name)}</div><button class="btn btn-ghost btn-sm" id="logout">Keluar</button></div></aside><main class="main"><header class="topbar"><img class="logo-mini" src="./assets/logo-ayo-bangun.jpeg"><select class="project-select" id="project-select">${projects.map(x=>`<option value="${x.id}" ${x.id===p?.id?'selected':''}>${esc(x.code)} • ${esc(x.name)}</option>`).join('')}</select><div class="spacer"></div><span class="status-pill ${firebaseReady?'online':''}">${firebaseReady?'● Firebase Sync':'● Mode Lokal'}</span></header><div class="content" id="content"></div></main></div><nav class="mobile-nav">${[['dashboard','⌂','Home'],['attendance','✓','Absen'],['usage','⇧','Material'],['progress','◫','Progress'],['reports','≡','Laporan']].filter(x=>NAV[x[0]]?.[2].includes(user.role)).map(x=>`<button data-page="${x[0]}" class="${page===x[0]?'active':''}"><span>${x[1]}</span><span>${x[2]}</span></button>`).join('')}</nav>`; $$('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;renderApp()}); $('#project-select').onchange=e=>{Store.setActiveProject(e.target.value)}; $('#logout').onclick=async()=>{if(firebaseReady)await FirebaseBridge.signOut().catch(()=>{});Store.logout();firebaseReady=false;renderLogin()}; renderPage();}

function head(title,desc='',actions=''){return `<div class="page-head"><div><h1>${title}</h1><p>${desc}</p></div><div class="actions">${actions}</div></div>`}
function renderPage(){const fn={dashboard:dashboardPage,projects:projectsPage,materials:materialsPage,stock:stockPage,usage:usagePage,attendance:attendancePage,progress:progressPage,issues:issuesPage,reports:reportsPage,approvals:approvalsPage,rab:rabPage,purchases:purchasesPage,suppliers:suppliersPage,tools:toolsPage,hse:hsePage,users:usersPage,audit:auditPage,settings:settingsPage}[page]||dashboardPage; $('#content').innerHTML=fn(); wirePage();}

function dashboardPage(){const p=Store.activeProject(); if(!p)return head('Dashboard')+`<div class="empty">Belum ada proyek.</div>`; const progress=weightedProgress(),att=todayRows('attendance').filter(x=>x.status==='hadir').length,pending=projectRows('stock').filter(x=>x.status==='pending').length+projectRows('usage').filter(x=>x.status==='pending').length,issues=projectRows('issues').filter(x=>x.status!=='closed').length; const usageCost=projectRows('usage').filter(x=>x.status==='approved').reduce((s,x)=>s+Number(x.qty||0)*Number(x.unitPrice||byId('materials',x.materialId)?.defaultPrice||0),0); const targets=projectRows('progress').slice().sort((a,b)=>(a.dueDate||'').localeCompare(b.dueDate||'')).slice(0,5);return head('Dashboard',`${p.name} • ${p.location||'-'}`)+`<div class="grid grid-4"><div class="card metric"><div class="label">Progress Terbobot</div><div class="value">${num(progress)}%</div><div class="progressbar"><span style="width:${Math.min(100,progress)}%"></span></div></div><div class="card metric"><div class="label">Tenaga Hadir Hari Ini</div><div class="value">${att}</div><div class="sub">orang tercatat hadir</div></div><div class="card metric"><div class="label">Menunggu Approval</div><div class="value">${pending}</div><div class="sub">stok masuk + pemakaian</div></div><div class="card metric"><div class="label">Kendala Terbuka</div><div class="value">${issues}</div><div class="sub">perlu tindak lanjut</div></div></div><div class="grid grid-2" style="margin-top:16px"><div class="card"><h3 class="section-title">Ringkasan Biaya Material</h3><div class="kpi-row"><span>Nilai kontrak</span><strong>${money(p.contractValue)}</strong></div><div class="kpi-row"><span>Estimasi material terpakai</span><strong>${money(usageCost)}</strong></div><div class="kpi-row"><span>RAB terdaftar</span><strong>${money(projectRows('rab').reduce((s,x)=>s+Number(x.qty||0)*Number(x.unitPrice||0),0))}</strong></div></div><div class="card"><h3 class="section-title">Target Pekerjaan Terdekat</h3>${targets.length?`<div class="list">${targets.map(x=>`<div class="list-item"><strong>${esc(x.name)}</strong><small>${num(x.percent)}% • Target ${date(x.dueDate)}</small><div class="progressbar" style="margin-top:8px"><span style="width:${Math.min(100,Number(x.percent||0))}%"></span></div></div>`).join('')}</div>`:`<div class="empty">Target pekerjaan belum dibuat.</div>`}</div></div>`}

function projectsPage(){const rows=Store.list('projects');return head('Proyek','Kelola beberapa proyek dengan data, target, material dan laporan terpisah.','<button class="btn btn-primary" data-action="project-add">+ Proyek</button>')+table(['Kode','Nama','Lokasi','Klien','Nilai Kontrak','Periode','Status',''],rows.map(x=>[esc(x.code),`<strong>${esc(x.name)}</strong><br><small class="muted">${esc(x.description||'')}</small>`,esc(x.location||'-'),esc(x.client||'-'),money(x.contractValue),`${date(x.startDate)} - ${date(x.endDate)}`,badge(x.status),actions('project',x.id,true)]))}

function materialsPage(){const rows=Store.list('materials').filter(x=>x.active!==false);return head('Katalog Material','Master material konstruksi umum. Harga, satuan, stok minimum dan item dapat disesuaikan oleh Admin/Owner.',can(['owner','admin'])?'<button class="btn btn-primary" data-action="material-add">+ Material</button>':'')+`<div class="toolbar"><input id="material-search" placeholder="Cari material / kode / kategori..."><select id="material-category"><option value="">Semua kategori</option>${[...new Set(rows.map(x=>x.category))].sort().map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div id="material-table">${materialTable(rows)}</div>`}
function materialTable(rows){return table(['Kode','Material','Kategori','Satuan','Harga Dasar','Stok Proyek','Min. Stok',''],rows.map(x=>[esc(x.code),`<strong>${esc(x.name)}</strong>`,esc(x.category),esc(x.unit),money(x.defaultPrice),num(stockBalance(x.id)),num(x.minStock),can(['owner','admin'])?actions('material',x.id,true):'']))}

function stockPage(){const rows=projectRows('stock').slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));return head('Stok Material Masuk','Mandor dapat input penerimaan/opname stok. Input Mandor menunggu verifikasi Admin/Owner.','<button class="btn btn-primary" data-action="stock-add">+ Input Stok</button>')+table(['Tanggal','Material','Qty','Satuan','Jenis','Supplier/PO','Status','Input Oleh',''],rows.map(x=>[date(x.date),matName(x.materialId),num(x.qty),esc(x.unit),esc(x.type||'Penerimaan'),esc(x.source||'-'),badge(x.status),userName(x.createdBy),can(['owner','admin'])?approvalActions('stock',x):actions('stock',x.id,x.status==='pending')]))}
function usagePage(){const rows=projectRows('usage').slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));return head('Penggunaan Material','Catat material keluar/terpakai per pekerjaan dan lokasi.','<button class="btn btn-primary" data-action="usage-add">+ Pemakaian</button>')+table(['Tanggal','Material','Qty','Pekerjaan/Lokasi','Harga','Status','Input Oleh',''],rows.map(x=>[date(x.date),matName(x.materialId),`${num(x.qty)} ${esc(x.unit)}`,`<strong>${esc(x.work||'-')}</strong><br><small class="muted">${esc(x.location||'')}</small>`,money(x.unitPrice),badge(x.status),userName(x.createdBy),can(['owner','admin'])?approvalActions('usage',x):actions('usage',x.id,x.status==='pending')]))}
function attendancePage(){const rows=projectRows('attendance').slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));return head('Absensi Tenaga Kerja','Absensi dapat ditambah dan diedit oleh Owner, Admin, maupun Mandor.','<button class="btn btn-primary" data-action="attendance-add">+ Absensi</button>')+table(['Tanggal','Nama','Jabatan','Status','Jam Masuk','Jam Keluar','Lembur','Upah Harian',''],rows.map(x=>[date(x.date),esc(x.workerName),esc(x.position||'-'),badge(x.status==='hadir'?'approved':x.status),esc(x.checkIn||'-'),esc(x.checkOut||'-'),`${num(x.overtime||0)} jam`,money(x.dailyWage),actions('attendance',x.id,true)]))}
function progressPage(){const rows=projectRows('progress').slice().sort((a,b)=>(a.dueDate||'').localeCompare(b.dueDate||''));return head('Progress & Target','Target harian/mingguan, volume, bobot pekerjaan dan aktual. Mandor dapat memperbarui aktual. ',can(['owner','admin'])?'<button class="btn btn-primary" data-action="progress-add">+ Target Pekerjaan</button>':'')+table(['Pekerjaan','Bobot','Target / Harian','Aktual','Progress','Target Tanggal','Catatan',''],rows.map(x=>[esc(x.name),`${num(x.weight)}%`,`${num(x.targetQty)} ${esc(x.unit)}<br><small class=\"muted\">Harian: ${num(x.dailyTargetQty||0)} ${esc(x.unit)}</small>`,`${num(x.actualQty)} ${esc(x.unit)}`,`<strong>${num(x.percent)}%</strong><div class="progressbar"><span style="width:${Math.min(100,Number(x.percent||0))}%"></span></div>`,date(x.dueDate),`${esc(x.notes||'-')}${x.photoUrl?`<br><a href=\"${esc(x.photoUrl)}\" target=\"_blank\" class=\"text-gold\">📷 Foto</a>`:''}`,`<button class="btn btn-sm" data-action="progress-update" data-id="${x.id}">${can(['owner','admin'])?'Edit':'Update'}</button>`]))}
function issuesPage(){const rows=projectRows('issues').slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));return head('Kendala Pekerjaan','Catat kendala, risiko, tindakan, PIC dan status penyelesaian.','<button class="btn btn-primary" data-action="issue-add">+ Kendala</button>')+table(['Tanggal','Kategori','Kendala','Dampak','Tindakan/PIC','Status',''],rows.map(x=>[date(x.date),esc(x.category),`<strong>${esc(x.title)}</strong><br><small class="muted">${esc(x.description||'')}</small>`,esc(x.impact||'-'),`${esc(x.action||'-')}<br><small class="muted">PIC: ${esc(x.pic||'-')}</small>${x.photoUrl?`<br><a href=\"${esc(x.photoUrl)}\" target=\"_blank\" class=\"text-gold\">📷 Foto</a>`:''}`,badge(x.status),actions('issue',x.id,true)]))}
function reportsPage(){const rows=projectRows('reports').slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));return head('Laporan Harian','Rekap progress, tenaga kerja, material, kendala, cuaca, rencana kerja dan WhatsApp.','<button class="btn" data-action="report-auto">Buat dari Data Hari Ini</button><button class="btn btn-primary" data-action="report-add">+ Laporan Manual</button>')+table(['Tanggal','Cuaca','Progress','Tenaga','Ringkasan','Status','WhatsApp',''],rows.map(x=>[date(x.date),esc(x.weather||'-'),`${num(x.progress)}%`,`${x.workers||0} orang`,`<strong>${esc(x.workSummary||'-')}</strong><br><small class="muted">${esc(x.planTomorrow||'')}</small>`,badge(x.status),`${x.photoUrl?`<a href=\"${esc(x.photoUrl)}\" target=\"_blank\" class=\"btn btn-sm\">Foto</a> `:''}<button class="btn btn-sm btn-ok" data-action="report-wa" data-id="${x.id}">Kirim</button> ${actions('report',x.id,true)}`]))}
function approvalsPage(){const s=projectRows('stock').filter(x=>x.status==='pending'),u=projectRows('usage').filter(x=>x.status==='pending');return head('Approval','Verifikasi stok masuk dan pemakaian material yang diajukan lapangan.')+`<div class="grid grid-2"><div class="card"><h3 class="section-title">Stok Masuk (${s.length})</h3>${s.length?`<div class="list">${s.map(x=>`<div class="list-item"><strong>${matName(x.materialId)} • ${num(x.qty)} ${esc(x.unit)}</strong><small>${date(x.date)} • ${userName(x.createdBy)}</small><div class="actions" style="margin-top:10px">${approvalActions('stock',x)}</div></div>`).join('')}</div>`:'<div class="empty">Tidak ada approval.</div>'}</div><div class="card"><h3 class="section-title">Pemakaian (${u.length})</h3>${u.length?`<div class="list">${u.map(x=>`<div class="list-item"><strong>${matName(x.materialId)} • ${num(x.qty)} ${esc(x.unit)}</strong><small>${esc(x.work||'')} • ${userName(x.createdBy)}</small><div class="actions" style="margin-top:10px">${approvalActions('usage',x)}</div></div>`).join('')}</div>`:'<div class="empty">Tidak ada approval.</div>'}</div></div>`}
function rabPage(){const rows=projectRows('rab');return head('RAB / Anggaran','Item pekerjaan, volume, harga satuan dan nilai anggaran.','<button class="btn btn-primary" data-action="rab-add">+ Item RAB</button>')+`<div class="card metric" style="margin-bottom:16px"><div class="label">Total RAB</div><div class="value">${money(rows.reduce((s,x)=>s+Number(x.qty||0)*Number(x.unitPrice||0),0))}</div></div>`+table(['Kode','Pekerjaan','Volume','Satuan','Harga Satuan','Jumlah',''],rows.map(x=>[esc(x.code||'-'),esc(x.name),num(x.qty),esc(x.unit),money(x.unitPrice),money(Number(x.qty||0)*Number(x.unitPrice||0)),actions('rab',x.id,true)]))}
function purchasesPage(){const rows=projectRows('purchases');return head('Pembelian / Permintaan','Permintaan pembelian material dan status pemenuhan.','<button class="btn btn-primary" data-action="purchase-add">+ Permintaan</button>')+table(['Tanggal','Material/Item','Qty','Supplier','Estimasi','Status',''],rows.map(x=>[date(x.date),esc(x.item),`${num(x.qty)} ${esc(x.unit)}`,esc(x.supplier||'-'),money(x.estimatedCost),badge(x.status),actions('purchase',x.id,true)]))}
function suppliersPage(){const rows=Store.list('suppliers');return head('Supplier','Database pemasok material, alat dan jasa.','<button class="btn btn-primary" data-action="supplier-add">+ Supplier</button>')+table(['Nama','Kategori','Kontak','Telepon','Alamat','Catatan',''],rows.map(x=>[esc(x.name),esc(x.category||'-'),esc(x.contact||'-'),esc(x.phone||'-'),esc(x.address||'-'),esc(x.notes||'-'),actions('supplier',x.id,true)]))}
function toolsPage(){const rows=projectRows('tools');return head('Alat & Inventaris','Kontrol alat milik/sewa, kondisi dan penempatan.',can(['owner','admin'])?'<button class="btn btn-primary" data-action="tool-add">+ Alat</button>':'')+table(['Kode','Alat','Kepemilikan','Qty','Kondisi','Lokasi','Status',''],rows.map(x=>[esc(x.code||'-'),esc(x.name),esc(x.ownership||'-'),num(x.qty),esc(x.condition||'-'),esc(x.location||'-'),badge(x.status||'active'),can(['owner','admin'])?actions('tool',x.id,true):'']))}
function hsePage(){const rows=projectRows('hse').slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));return head('K3 / HSE','Toolbox meeting, inspeksi keselamatan, insiden dan tindakan koreksi.','<button class="btn btn-primary" data-action="hse-add">+ Catatan K3</button>')+table(['Tanggal','Jenis','Topik/Temuan','PIC','Tindakan','Status',''],rows.map(x=>[date(x.date),esc(x.type),esc(x.title),esc(x.pic||'-'),esc(x.action||'-'),badge(x.status),actions('hse',x.id,true)]))}
function usersPage(){const rows=Store.list('users');return head('Manajemen User','Owner/Admin dapat menambah beberapa Mandor dan mengatur password/akses.','<button class="btn btn-primary" data-action="user-add">+ User</button>')+table(['Username','Nama','Role','Status','Project Access',''],rows.map(x=>[esc(x.username),esc(x.name),`<span class="badge info">${esc(x.role)}</span>`,x.active!==false?badge('active'):'Nonaktif',esc((x.projectIds||[]).map(id=>byId('projects',id)?.name).filter(Boolean).join(', ')||'Semua / sesuai role'),`${(x.role!=='owner'||role()==='owner')?`<button class=\"btn btn-sm\" data-action=\"user-password\" data-id=\"${x.id}\">Password</button>`:''} ${(x.role!=='owner'||role()==='owner')?`<button class=\"btn btn-sm\" data-action=\"user-edit\" data-id=\"${x.id}\">Edit</button>`:''} ${(x.role!=='owner'||role()==='owner')?`<button class=\"btn btn-sm btn-danger\" data-action=\"delete\" data-collection=\"users\" data-id=\"${x.id}\">Hapus</button>`:''}`]))}
function auditPage(){const rows=Store.list('audit').slice(0,500);return head('Audit Log','Jejak perubahan data untuk kontrol administrasi.')+table(['Waktu','User','Role','Aksi','Modul','Objek'],rows.map(x=>[dt(x.timestamp),esc(x.userName),esc(x.role),esc(x.action),esc(x.collection),esc(x.label||x.recordId)]))}
function settingsPage(){const s=Store.get().settings;return head('Pengaturan','Identitas perusahaan, WhatsApp, backup, Firebase dan sinkronisasi lintas perangkat.')+`<div class="grid grid-2"><div class="card"><h3 class="section-title">Identitas & Laporan</h3><form id="settings-form"><div class="field"><label>Nama Perusahaan</label><input name="companyName" value="${esc(s.companyName)}"></div><div class="field"><label>Tagline</label><input name="tagline" value="${esc(s.tagline||'')}"></div><div class="field"><label>Nomor WhatsApp Laporan (pisahkan koma)</label><input name="wa" value="${esc((s.whatsappNumbers||[]).join(', '))}" placeholder="62812...,62813..."></div><div class="field"><label><input type="checkbox" name="whatsappAuto" ${s.whatsappAuto?'checked':''}> Tandai laporan untuk pengiriman otomatis oleh Firebase Function</label></div><button class="btn btn-primary">Simpan</button></form></div><div class="card"><h3 class="section-title">Firebase Sync</h3>${firebaseReady?'<div class="success-box">Firebase terhubung. Perubahan data akan disinkronkan realtime ke perangkat lain yang memakai organization ID dan project Firebase yang sama.</div>':'<div class="warning-box">Aplikasi tetap berjalan penuh dalam mode lokal. Untuk sinkronisasi multi-device, isi konfigurasi Firebase Anda. API key Firebase bukan password, tetapi Firestore Rules tetap wajib dipasang.</div>'}<form id="firebase-form" style="margin-top:14px"><div class="field"><label>Organization ID</label><input name="orgId" value="${esc(s.orgId||'ayo-bangun-id')}"></div><div class="field"><label>Firebase Config JSON</label><textarea name="config" placeholder='{"apiKey":"...","authDomain":"...","projectId":"...","storageBucket":"...","appId":"..."}'>${s.firebaseConfig?esc(JSON.stringify(s.firebaseConfig,null,2)):''}</textarea></div><button class="btn btn-primary">Simpan & Hubungkan</button></form></div><div class="card"><h3 class="section-title">Backup Data</h3><p class="muted">Export semua data lokal ke JSON atau import backup.</p><div class="actions"><button class="btn" data-action="backup-export">Export JSON</button><label class="btn btn-ghost">Import JSON<input id="backup-import" type="file" accept="application/json" hidden></label></div></div><div class="card"><h3 class="section-title">Keamanan</h3><p class="muted">Ganti password default segera. Password mode Firebase dikelola oleh Firebase Authentication. Password lokal hanya untuk mode demo/offline.</p><button class="btn" data-action="user-password" data-id="${Store.currentUser().id}">Ganti Password Saya</button></div></div>`}

function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty">Belum ada data.</td></tr>`}</tbody></table></div>`}
function actions(type,id,edit=true){return `<div class="actions nowrap">${edit?`<button class="btn btn-sm" data-action="${type}-edit" data-id="${id}">Edit</button>`:''}${can(['owner','admin'])?`<button class="btn btn-sm btn-danger" data-action="delete" data-collection="${typeMap(type)}" data-id="${id}">Hapus</button>`:''}</div>`}
function typeMap(t){return {project:'projects',material:'materials',attendance:'attendance',issue:'issues',report:'reports',rab:'rab',purchase:'purchases',supplier:'suppliers',tool:'tools',hse:'hse',user:'users',stock:'stock',usage:'usage'}[t]||t}
function approvalActions(c,x){return `<button class="btn btn-sm btn-ok" data-action="approve" data-collection="${c}" data-id="${x.id}">Setujui</button><button class="btn btn-sm btn-danger" data-action="reject" data-collection="${c}" data-id="${x.id}">Tolak</button>`}

function openModal(title,body,onSave,saveText='Simpan'){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<div class="modal"><div class="modal-head"><h3>${title}</h3><button class="close">×</button></div><form><div class="modal-body">${body}</div><div class="modal-foot"><button type="button" class="btn btn-ghost close2">Batal</button><button class="btn btn-primary">${saveText}</button></div></form></div>`;document.body.append(wrap);$('.close',wrap).onclick=$('.close2',wrap).onclick=()=>wrap.remove();$('form',wrap).onsubmit=async e=>{e.preventDefault();try{await onSave(new FormData(e.target),wrap);wrap.remove();toast('Data tersimpan','ok');renderApp()}catch(err){toast(err.message||'Gagal menyimpan','bad')}};return wrap}
const fld=(name,label,value='',type='text',opts='')=>`<div class="field"><label>${label}</label><input name="${name}" type="${type}" value="${esc(value)}" ${opts}></div>`;
const sel=(name,label,value,options)=>`<div class="field"><label>${label}</label><select name="${name}">${options.map(o=>{const v=Array.isArray(o)?o[0]:o,t=Array.isArray(o)?o[1]:o;return `<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`}).join('')}</select></div>`;
const area=(name,label,value='')=>`<div class="field full"><label>${label}</label><textarea name="${name}">${esc(value)}</textarea></div>`;
const photoField=(label='Foto Lapangan')=>`<div class="field full"><label>${label}</label><input name="photo" type="file" accept="image/*" capture="environment"><div class="hint">Foto akan dikompresi. Pada mode Firebase disimpan di Firebase Storage.</div></div>`;
function materialOptions(value=''){return Store.list('materials').filter(x=>x.active!==false).map(x=>[x.id,`${x.code} • ${x.name}`])}
function unitOptions(value=''){return UNITS.map(x=>[x,x])}

function wirePage(){
 $$('[data-action]').forEach(b=>b.onclick=()=>handleAction(b.dataset.action,b.dataset));
 if($('#material-search')){$('#material-search').oninput=$('#material-category').onchange=()=>{const q=$('#material-search').value.toLowerCase(),c=$('#material-category').value;const rows=Store.list('materials').filter(x=>x.active!==false&&(!c||x.category===c)&&(!q||`${x.code} ${x.name} ${x.category}`.toLowerCase().includes(q)));$('#material-table').innerHTML=materialTable(rows);wirePage()}}
 if($('#settings-form'))$('#settings-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await Store.updateSettings({companyName:f.get('companyName'),tagline:f.get('tagline'),whatsappNumbers:String(f.get('wa')||'').split(',').map(x=>x.trim().replace(/^\+/,'')).filter(Boolean),whatsappAuto:f.get('whatsappAuto')==='on'});toast('Pengaturan disimpan','ok')};
 if($('#firebase-form'))$('#firebase-form').onsubmit=async e=>{e.preventDefault();if(role()!=='owner'){toast('Konfigurasi Firebase hanya untuk Owner','bad');return}const f=new FormData(e.target);try{const cfg=JSON.parse(f.get('config'));await Store.updateSettings({orgId:f.get('orgId'),firebaseConfig:cfg});await ensureFirebase();toast('Firebase terhubung. Login ulang untuk autentikasi dan realtime sync.','ok');renderApp()}catch(er){toast(er.message,'bad')}};
 if($('#backup-import'))$('#backup-import').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());Store.importData(data);toast('Backup berhasil diimpor','ok');renderApp()}catch(er){toast(er.message,'bad')}};
}

async function handleAction(a,d){
 if(a==='delete'){if(d.collection==='users'){const target=byId('users',d.id);if(target?.role==='owner'&&role()!=='owner'){toast('Admin tidak dapat menghapus Owner','bad');return}}if(confirm('Hapus data ini?'))await Store.remove(d.collection,d.id);return}
 if(a==='approve'||a==='reject'){const x=Store.find(d.collection,d.id);await Store.upsert(d.collection,{...x,status:a==='approve'?'approved':'rejected',approvedBy:Store.currentUser().id,approvedAt:Store.now()});return}
 if(a==='backup-export'){const blob=new Blob([JSON.stringify(Store.exportData(),null,2)],{type:'application/json'});const u=URL.createObjectURL(blob);const link=document.createElement('a');link.href=u;link.download=`ayo-bangun-backup-${today()}.json`;link.click();URL.revokeObjectURL(u);return}
 if(a==='project-add'||a==='project-edit') return projectModal(a.endsWith('edit')?byId('projects',d.id):{});
 if(a==='material-add'||a==='material-edit') return materialModal(a.endsWith('edit')?byId('materials',d.id):{});
 if(a==='stock-add'||a==='stock-edit') return stockModal(a.endsWith('edit')?byId('stock',d.id):{});
 if(a==='usage-add'||a==='usage-edit') return usageModal(a.endsWith('edit')?byId('usage',d.id):{});
 if(a==='attendance-add'||a==='attendance-edit') return attendanceModal(a.endsWith('edit')?byId('attendance',d.id):{});
 if(a==='progress-add'||a==='progress-update') return progressModal(a==='progress-update'?byId('progress',d.id):{});
 if(a==='issue-add'||a==='issue-edit') return issueModal(a.endsWith('edit')?byId('issues',d.id):{});
 if(a==='report-add'||a==='report-edit') return reportModal(a.endsWith('edit')?byId('reports',d.id):{});
 if(a==='report-auto') return autoReport();
 if(a==='report-wa') return shareWhatsApp(byId('reports',d.id));
 if(a==='rab-add'||a==='rab-edit') return rabModal(a.endsWith('edit')?byId('rab',d.id):{});
 if(a==='purchase-add'||a==='purchase-edit') return purchaseModal(a.endsWith('edit')?byId('purchases',d.id):{});
 if(a==='supplier-add'||a==='supplier-edit') return supplierModal(a.endsWith('edit')?byId('suppliers',d.id):{});
 if(a==='tool-add'||a==='tool-edit') return toolModal(a.endsWith('edit')?byId('tools',d.id):{});
 if(a==='hse-add'||a==='hse-edit') return hseModal(a.endsWith('edit')?byId('hse',d.id):{});
 if(a==='user-add'||a==='user-edit') return userModal(a.endsWith('edit')?byId('users',d.id):{});
 if(a==='user-password'){const target=byId('users',d.id);if(target?.role==='owner'&&role()!=='owner'){toast('Hanya Owner dapat mengganti password Owner','bad');return}return passwordModal(target)}
}

function projectModal(x){openModal(x.id?'Edit Proyek':'Tambah Proyek',`<div class="form-grid">${fld('code','Kode Proyek',x.code||'', 'text','required')}${fld('name','Nama Proyek',x.name||'','text','required')}${fld('location','Lokasi',x.location||'')}${fld('client','Klien / Pemberi Kerja',x.client||'')}${fld('contractValue','Nilai Kontrak',x.contractValue||0,'number','min="0"')}${sel('status','Status',x.status||'active',[['active','Aktif'],['done','Selesai'],['archived','Arsip']])}${fld('startDate','Tanggal Mulai',x.startDate||today(),'date')}${fld('endDate','Target Selesai',x.endDate||'','date')}${area('description','Keterangan Proyek',x.description||'')}</div>`,async f=>{await Store.upsert('projects',{...x,id:x.id||Store.newId('prj'),code:f.get('code'),name:f.get('name'),location:f.get('location'),client:f.get('client'),contractValue:+f.get('contractValue'),status:f.get('status'),startDate:f.get('startDate'),endDate:f.get('endDate'),description:f.get('description')})})}
function materialModal(x){openModal(x.id?'Edit Material':'Tambah Material',`<div class="form-grid">${fld('code','Kode',x.code||'','text','required')}${fld('name','Nama Material',x.name||'','text','required')}${fld('category','Kategori',x.category||'','text','required')}${sel('unit','Satuan',x.unit||'buah',unitOptions())}${fld('defaultPrice','Harga Dasar',x.defaultPrice||0,'number','min="0"')}${fld('minStock','Stok Minimum',x.minStock||0,'number','step="0.01"')}${fld('brand','Merk/Spesifikasi',x.brand||'')}${sel('active','Status',String(x.active!==false),[['true','Aktif'],['false','Nonaktif']])}</div>`,async f=>{await Store.upsert('materials',{...x,id:x.id||Store.newId('mat'),code:f.get('code'),name:f.get('name'),category:f.get('category'),unit:f.get('unit'),defaultPrice:+f.get('defaultPrice'),minStock:+f.get('minStock'),brand:f.get('brand'),active:f.get('active')==='true',projectId:null})})}
function stockModal(x){const mandor=role()==='mandor';openModal(x.id?'Edit Stok':'Input Stok Material',`<div class="form-grid">${fld('date','Tanggal',x.date||today(),'date','required')}${sel('materialId','Material',x.materialId||'',materialOptions())}${fld('qty','Volume / Qty',x.qty||'','number','step="0.001" min="0" required')}${sel('unit','Satuan',x.unit||'zak',unitOptions())}${sel('type','Jenis',x.type||'Penerimaan',[['Penerimaan','Penerimaan'],['Opname','Opname/Koreksi +'],['Retur','Retur masuk']])}${fld('source','Supplier / PO / Sumber',x.source||'')}${area('notes','Catatan / Nomor Surat Jalan',x.notes||'')}</div>`,async f=>{const m=byId('materials',f.get('materialId'));await Store.upsert('stock',{...x,id:x.id||Store.newId('stk'),projectId:activeId(),date:f.get('date'),materialId:f.get('materialId'),qty:+f.get('qty'),unit:f.get('unit')||m?.unit,type:f.get('type'),source:f.get('source'),notes:f.get('notes'),status:x.status||(mandor?'pending':'approved'),createdBy:x.createdBy||Store.currentUser().id})})}
function usageModal(x){const mandor=role()==='mandor';openModal(x.id?'Edit Pemakaian':'Input Penggunaan Material',`<div class="form-grid">${fld('date','Tanggal',x.date||today(),'date','required')}${sel('materialId','Material',x.materialId||'',materialOptions())}${fld('qty','Volume / Qty',x.qty||'','number','step="0.001" min="0" required')}${sel('unit','Satuan',x.unit||'zak',unitOptions())}${sel('work','Pekerjaan',x.work||'',WORK_TYPES)}${fld('location','Zona / Lokasi Kerja',x.location||'')}${fld('unitPrice','Harga Satuan (opsional)',x.unitPrice||0,'number','min="0"')}${area('notes','Catatan',x.notes||'')}</div>`,async f=>{const m=byId('materials',f.get('materialId'));await Store.upsert('usage',{...x,id:x.id||Store.newId('use'),projectId:activeId(),date:f.get('date'),materialId:f.get('materialId'),qty:+f.get('qty'),unit:f.get('unit')||m?.unit,work:f.get('work'),location:f.get('location'),unitPrice:+f.get('unitPrice')||m?.defaultPrice||0,notes:f.get('notes'),status:x.status||(mandor?'pending':'approved'),createdBy:x.createdBy||Store.currentUser().id})})}
function attendanceModal(x){openModal(x.id?'Edit Absensi':'Tambah Absensi',`<div class="form-grid">${fld('date','Tanggal',x.date||today(),'date','required')}${fld('workerName','Nama Pekerja',x.workerName||'','text','required')}${fld('position','Jabatan / Tukang',x.position||'')}${sel('status','Status',x.status||'hadir',[['hadir','Hadir'],['izin','Izin'],['sakit','Sakit'],['alpha','Alpha']])}${fld('checkIn','Jam Masuk',x.checkIn||'07:00','time')}${fld('checkOut','Jam Keluar',x.checkOut||'16:00','time')}${fld('overtime','Lembur (jam)',x.overtime||0,'number','step="0.5" min="0"')}${fld('dailyWage','Upah Harian',x.dailyWage||0,'number','min="0"')}${area('notes','Catatan',x.notes||'')}</div>`,async f=>{await Store.upsert('attendance',{...x,id:x.id||Store.newId('att'),projectId:activeId(),date:f.get('date'),workerName:f.get('workerName'),position:f.get('position'),status:f.get('status'),checkIn:f.get('checkIn'),checkOut:f.get('checkOut'),overtime:+f.get('overtime'),dailyWage:+f.get('dailyWage'),notes:f.get('notes'),createdBy:x.createdBy||Store.currentUser().id})})}
function progressModal(x){const isMandor=role()==='mandor';openModal(x.id?'Update Progress':'Tambah Target',`<div class="form-grid">${isMandor?`<div class="field full"><label>Pekerjaan</label><input value="${esc(x.name||'')}" disabled></div>`:sel('name','Jenis/Pekerjaan',x.name||WORK_TYPES[0],WORK_TYPES)}${isMandor?'':fld('weight','Bobot (%)',x.weight||0,'number','step="0.01" min="0"')}${isMandor?'':fld('targetQty','Target Volume',x.targetQty||0,'number','step="0.001" min="0"')}${isMandor?'':fld('dailyTargetQty','Target Harian',x.dailyTargetQty||0,'number','step="0.001" min="0"')}${isMandor?'':sel('unit','Satuan',x.unit||'m2',unitOptions())}${fld('actualQty','Aktual Volume',x.actualQty||0,'number','step="0.001" min="0"')}${isMandor?'':fld('dueDate','Target Tanggal',x.dueDate||today(),'date')}${area('notes','Catatan Lapangan',x.notes||'')}${photoField('Foto Progress')}</div>`,async f=>{const target=isMandor?Number(x.targetQty||0):+f.get('targetQty');const actual=+f.get('actualQty');await Store.upsert('progress',{...x,id:x.id||Store.newId('prg'),projectId:activeId(),name:isMandor?x.name:f.get('name'),weight:isMandor?x.weight:+f.get('weight'),targetQty:target,unit:isMandor?x.unit:f.get('unit'),actualQty:actual,dailyTargetQty:isMandor?x.dailyTargetQty:+f.get('dailyTargetQty'),percent:target?Math.min(100,actual/target*100):0,dueDate:isMandor?x.dueDate:f.get('dueDate'),notes:f.get('notes'),photoUrl:await savePhoto(f,x.photoUrl,'progress')})})}
function issueModal(x){openModal(x.id?'Edit Kendala':'Tambah Kendala',`<div class="form-grid">${fld('date','Tanggal',x.date||today(),'date','required')}${sel('category','Kategori',x.category||'Teknis',['Teknis','Cuaca','Material','Tenaga Kerja','Alat','Desain','K3','Akses/Lingkungan','Koordinasi','Lainnya'])}${fld('title','Judul Kendala',x.title||'','text','required')}${sel('status','Status',x.status||'open',[['open','Terbuka'],['closed','Selesai']])}${area('description','Deskripsi',x.description||'')}${fld('impact','Dampak',x.impact||'')}${fld('pic','PIC',x.pic||'')}${area('action','Tindakan / Solusi',x.action||'')}${photoField('Foto Kendala')}</div>`,async f=>{await Store.upsert('issues',{...x,id:x.id||Store.newId('iss'),projectId:activeId(),date:f.get('date'),category:f.get('category'),title:f.get('title'),status:f.get('status'),description:f.get('description'),impact:f.get('impact'),pic:f.get('pic'),action:f.get('action'),photoUrl:await savePhoto(f,x.photoUrl,'issues')})})}
function reportModal(x){openModal(x.id?'Edit Laporan Harian':'Laporan Harian',`<div class="form-grid">${fld('date','Tanggal',x.date||today(),'date','required')}${sel('weather','Cuaca',x.weather||'Cerah',['Cerah','Berawan','Hujan Ringan','Hujan Lebat','Campuran'])}${fld('progress','Progress Proyek (%)',x.progress??weightedProgress(),'number','step="0.01" min="0" max="100"')}${fld('workers','Jumlah Tenaga',x.workers??todayRows('attendance').filter(a=>a.status==='hadir').length,'number','min="0"')}${area('workSummary','Pekerjaan Hari Ini',x.workSummary||'')}${area('materialSummary','Material Digunakan',x.materialSummary||materialSummary(today()))}${area('issues','Kendala',x.issues||issueSummary(today()))}${area('planTomorrow','Rencana Besok',x.planTomorrow||'')}${photoField('Foto Dokumentasi')}${sel('status','Status',x.status||'approved',[['draft','Draft'],['approved','Disetujui']])}</div>`,async f=>{await Store.upsert('reports',{...x,id:x.id||Store.newId('rpt'),projectId:activeId(),date:f.get('date'),weather:f.get('weather'),progress:+f.get('progress'),workers:+f.get('workers'),workSummary:f.get('workSummary'),materialSummary:f.get('materialSummary'),issues:f.get('issues'),planTomorrow:f.get('planTomorrow'),status:f.get('status'),whatsappAuto:Store.get().settings.whatsappAuto,waSent:x.waSent||false,photoUrl:await savePhoto(f,x.photoUrl,'reports')})})}
async function autoReport(){const d=today();const works=projectRows('progress').filter(x=>Number(x.actualQty)>0).map(x=>`${x.name}: ${num(x.actualQty)} ${x.unit} (${num(x.percent)}%)`).join('\n');await Store.upsert('reports',{id:Store.newId('rpt'),projectId:activeId(),date:d,weather:'Cerah',progress:weightedProgress(),workers:todayRows('attendance').filter(a=>a.status==='hadir').length,workSummary:works||'Update pekerjaan belum diinput.',materialSummary:materialSummary(d),issues:issueSummary(d),planTomorrow:'',status:'approved',whatsappAuto:Store.get().settings.whatsappAuto,waSent:false});toast('Laporan hari ini dibuat dari data proyek','ok')}
function materialSummary(d){const rows=projectRows('usage').filter(x=>x.status==='approved'&&x.date===d);return rows.length?rows.map(x=>`${matName(x.materialId)}: ${num(x.qty)} ${x.unit} (${x.work||'-'})`).join('\n'):'Tidak ada pemakaian material terverifikasi.'}
function issueSummary(d){const rows=projectRows('issues').filter(x=>x.date===d);return rows.length?rows.map(x=>`${x.title}: ${x.description||x.impact||'-'}`).join('\n'):'Tidak ada kendala tercatat.'}
function reportText(r){const p=Store.activeProject();return `*AYO BANGUN.ID CONTRACTOR*\nLAPORAN HARIAN PROYEK\n\nProject: ${p?.name||'-'}\nKode: ${p?.code||'-'}\nLokasi: ${p?.location||'-'}\nTanggal: ${date(r.date)}\nCuaca: ${r.weather||'-'}\n\n*PROGRESS*\n${num(r.progress)}%\n\n*TENAGA KERJA*\n${r.workers||0} orang\n\n*PEKERJAAN HARI INI*\n${r.workSummary||'-'}\n\n*MATERIAL DIGUNAKAN*\n${r.materialSummary||'-'}\n\n*KENDALA*\n${r.issues||'-'}\n\n*RENCANA BESOK*\n${r.planTomorrow||'-'}\n\n${r.photoUrl?`\n\nDOKUMENTASI\n${r.photoUrl}`:''}\n\nDikirim dari Ayo Bangun.ID Contractor`}
function shareWhatsApp(r){const n=(Store.get().settings.whatsappNumbers||[])[0]||'';const text=encodeURIComponent(reportText(r));window.open(n?`https://wa.me/${n}?text=${text}`:`https://wa.me/?text=${text}`,'_blank','noopener');}
function rabModal(x){openModal(x.id?'Edit RAB':'Tambah Item RAB',`<div class="form-grid">${fld('code','Kode',x.code||'')}${fld('name','Pekerjaan',x.name||'','text','required')}${fld('qty','Volume',x.qty||0,'number','step="0.001"')}${sel('unit','Satuan',x.unit||'m2',unitOptions())}${fld('unitPrice','Harga Satuan',x.unitPrice||0,'number','min="0"')}${area('notes','Spesifikasi/Catatan',x.notes||'')}</div>`,async f=>Store.upsert('rab',{...x,id:x.id||Store.newId('rab'),projectId:activeId(),code:f.get('code'),name:f.get('name'),qty:+f.get('qty'),unit:f.get('unit'),unitPrice:+f.get('unitPrice'),notes:f.get('notes')}))}
function purchaseModal(x){openModal(x.id?'Edit Permintaan':'Permintaan Pembelian',`<div class="form-grid">${fld('date','Tanggal',x.date||today(),'date')}${fld('item','Material / Item',x.item||'','text','required')}${fld('qty','Qty',x.qty||0,'number','step="0.001"')}${sel('unit','Satuan',x.unit||'pcs',unitOptions())}${fld('supplier','Supplier',x.supplier||'')}${fld('estimatedCost','Estimasi Biaya',x.estimatedCost||0,'number')}${sel('status','Status',x.status||'pending',[['pending','Menunggu'],['approved','Disetujui'],['done','Selesai'],['rejected','Ditolak']])}${area('notes','Catatan',x.notes||'')}</div>`,async f=>Store.upsert('purchases',{...x,id:x.id||Store.newId('pur'),projectId:activeId(),date:f.get('date'),item:f.get('item'),qty:+f.get('qty'),unit:f.get('unit'),supplier:f.get('supplier'),estimatedCost:+f.get('estimatedCost'),status:f.get('status'),notes:f.get('notes')}))}
function supplierModal(x){openModal(x.id?'Edit Supplier':'Tambah Supplier',`<div class="form-grid">${fld('name','Nama Supplier',x.name||'','text','required')}${fld('category','Kategori',x.category||'Material')}${fld('contact','Nama Kontak',x.contact||'')}${fld('phone','Telepon / WhatsApp',x.phone||'')}${fld('address','Alamat',x.address||'')}${area('notes','Catatan',x.notes||'')}</div>`,async f=>Store.upsert('suppliers',{...x,id:x.id||Store.newId('sup'),name:f.get('name'),category:f.get('category'),contact:f.get('contact'),phone:f.get('phone'),address:f.get('address'),notes:f.get('notes')}))}
function toolModal(x){openModal(x.id?'Edit Alat':'Tambah Alat',`<div class="form-grid">${fld('code','Kode Alat',x.code||'')}${fld('name','Nama Alat',x.name||'','text','required')}${sel('ownership','Kepemilikan',x.ownership||'Milik',['Milik','Sewa','Pinjam'])}${fld('qty','Qty',x.qty||1,'number','min="0"')}${sel('condition','Kondisi',x.condition||'Baik',['Baik','Perlu Servis','Rusak'])}${fld('location','Lokasi',x.location||'')}${sel('status','Status',x.status||'active',[['active','Aktif'],['done','Tidak Aktif']])}${area('notes','Catatan',x.notes||'')}</div>`,async f=>Store.upsert('tools',{...x,id:x.id||Store.newId('tool'),projectId:activeId(),code:f.get('code'),name:f.get('name'),ownership:f.get('ownership'),qty:+f.get('qty'),condition:f.get('condition'),location:f.get('location'),status:f.get('status'),notes:f.get('notes')}))}
function hseModal(x){openModal(x.id?'Edit Catatan K3':'Tambah Catatan K3',`<div class="form-grid">${fld('date','Tanggal',x.date||today(),'date')}${sel('type','Jenis',x.type||'Toolbox Meeting',['Toolbox Meeting','Inspeksi','Near Miss','Insiden','Permit to Work','Housekeeping'])}${fld('title','Topik / Temuan',x.title||'','text','required')}${fld('pic','PIC',x.pic||'')}${area('action','Tindakan / Hasil',x.action||'')}${sel('status','Status',x.status||'closed',[['open','Terbuka'],['closed','Selesai']])}</div>`,async f=>Store.upsert('hse',{...x,id:x.id||Store.newId('hse'),projectId:activeId(),date:f.get('date'),type:f.get('type'),title:f.get('title'),pic:f.get('pic'),action:f.get('action'),status:f.get('status')}))}
function userModal(x){
 const isEdit=!!x.id, projects=Store.list('projects').filter(p=>p.status!=='archived');
 const projectSelect=`<div class="field full"><label>Akses Project</label><select name="projectIds" multiple size="${Math.min(6,Math.max(3,projects.length))}">${projects.map(p=>`<option value="${p.id}" ${(x.projectIds||[]).includes(p.id)?'selected':''}>${esc(p.code)} • ${esc(p.name)}</option>`).join('')}</select><div class="hint">Untuk Mandor, pilih satu atau beberapa project. Jika kosong, aplikasi lokal menampilkan semua project.</div></div>`;
 openModal(isEdit?'Edit User':'Tambah User',`<div class="form-grid">${fld('username','Username',x.username||'','text',isEdit?'readonly':'required')}${fld('name','Nama',x.name||'','text','required')}${sel('role','Role',x.role||'mandor',role()==='owner'?[['owner','Owner'],['admin','Admin'],['mandor','Mandor']]:[['admin','Admin'],['mandor','Mandor']])}${sel('active','Status',String(x.active!==false),[['true','Aktif'],['false','Nonaktif']])}${projectSelect}${isEdit?'':fld('password','Password Awal','','password',`required minlength="${firebaseReady?6:4}"`)}</div>`,async f=>{
  const projectIds=f.getAll('projectIds');
  if(!isEdit){
   if(firebaseReady){const res=await FirebaseBridge.createUser({username:f.get('username'),password:f.get('password'),name:f.get('name'),role:f.get('role'),projectIds});toast(`User Firebase dibuat: ${res.username}`,'ok')}
   else await Store.createLocalUser({username:f.get('username'),name:f.get('name'),role:f.get('role'),projectIds},f.get('password'));
  } else await Store.upsert('users',{...x,name:f.get('name'),role:f.get('role'),active:f.get('active')==='true',projectIds});
 })
}
function passwordModal(u){if(!u)return;const min=firebaseReady?6:4;openModal(`Ganti Password • ${esc(u.username)}`,`${fld('password','Password Baru','','password',`required minlength=\"${min}\"`)}${fld('confirm','Ulangi Password','','password',`required minlength=\"${min}\"`)}<div class="hint">${firebaseReady?'Password akan diperbarui pada Firebase Authentication.':'Password ini berlaku untuk mode lokal/offline.'}</div>`,async f=>{if(f.get('password')!==f.get('confirm'))throw new Error('Konfirmasi password tidak sama');if(firebaseReady){await FirebaseBridge.setUserPassword(u.id,f.get('password'));toast('Password Firebase diperbarui','ok')}else await Store.setPassword(u.id,f.get('password'))})}

async function compressImage(file){
 return await new Promise((resolve,reject)=>{const img=new Image(),u=URL.createObjectURL(file);img.onload=()=>{const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(u);b?resolve(new File([b],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg'})):reject(new Error('Gagal memproses foto'))},'image/jpeg',.75)};img.onerror=()=>reject(new Error('Foto tidak dapat dibaca'));img.src=u})
}
async function savePhoto(formData,oldUrl,folder){const f=formData.get('photo');if(!(f instanceof File)||!f.size)return oldUrl||'';const compressed=await compressImage(f);if(firebaseReady)return await FirebaseBridge.upload(activeId(),compressed,folder);if(compressed.size>800000)throw new Error('Foto masih terlalu besar untuk mode lokal. Aktifkan Firebase Storage.');return await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(compressed)})}

async function ensureFirebase(){if(firebaseReady)return;const s=Store.get().settings;if(!s.firebaseConfig)throw new Error('Firebase belum dikonfigurasi');await FirebaseBridge.connect(s.firebaseConfig,s.orgId,{onStatus:()=>{firebaseReady=true}});firebaseReady=true;}
init();
