export const MATERIAL_CATALOG = [
  ['SEM-001','Semen Portland PCC 40 kg','Semen & Binder','zak'],['SEM-002','Semen Portland OPC 50 kg','Semen & Binder','zak'],['SEM-003','Semen Putih 40 kg','Semen & Binder','zak'],['SEM-004','Mortar Perekat Bata Ringan','Semen & Binder','zak'],['SEM-005','Mortar Plester','Semen & Binder','zak'],['SEM-006','Mortar Acian','Semen & Binder','zak'],['SEM-007','Grout Non Shrink','Semen & Binder','zak'],
  ['AGR-001','Pasir Beton','Agregat','m3'],['AGR-002','Pasir Pasang','Agregat','m3'],['AGR-003','Pasir Urug','Agregat','m3'],['AGR-004','Batu Split 1/2','Agregat','m3'],['AGR-005','Batu Split 2/3','Agregat','m3'],['AGR-006','Screening','Agregat','m3'],['AGR-007','Batu Kali','Agregat','m3'],['AGR-008','Sirtu','Agregat','m3'],['AGR-009','Base Course A','Agregat','m3'],['AGR-010','Base Course B','Agregat','m3'],
  ['BET-175','Ready Mix K-175','Beton','m3'],['BET-225','Ready Mix K-225','Beton','m3'],['BET-250','Ready Mix K-250','Beton','m3'],['BET-300','Ready Mix K-300','Beton','m3'],['BET-350','Ready Mix K-350','Beton','m3'],['BET-400','Ready Mix K-400','Beton','m3'],['BET-ADD','Concrete Admixture','Beton','liter'],['BET-CUR','Curing Compound','Beton','liter'],
  ['BES-006','Besi Beton Polos Ø6 mm','Besi & Baja','batang'],['BES-008','Besi Beton Polos Ø8 mm','Besi & Baja','batang'],['BES-010','Besi Beton Polos Ø10 mm','Besi & Baja','batang'],['BES-012','Besi Beton Polos Ø12 mm','Besi & Baja','batang'],['BES-D10','Besi Beton Ulir D10','Besi & Baja','batang'],['BES-D13','Besi Beton Ulir D13','Besi & Baja','batang'],['BES-D16','Besi Beton Ulir D16','Besi & Baja','batang'],['BES-D19','Besi Beton Ulir D19','Besi & Baja','batang'],['BES-D22','Besi Beton Ulir D22','Besi & Baja','batang'],['BES-D25','Besi Beton Ulir D25','Besi & Baja','batang'],['BES-WM4','Wiremesh M4','Besi & Baja','lembar'],['BES-WM6','Wiremesh M6','Besi & Baja','lembar'],['BES-WM8','Wiremesh M8','Besi & Baja','lembar'],['BES-WM10','Wiremesh M10','Besi & Baja','lembar'],['BAJ-WF150','WF 150x75','Besi & Baja','batang'],['BAJ-WF200','WF 200x100','Besi & Baja','batang'],['BAJ-CNP75','CNP 75','Besi & Baja','batang'],['BAJ-CNP100','CNP 100','Besi & Baja','batang'],['BAJ-UNP100','UNP 100','Besi & Baja','batang'],['BAJ-H40','Hollow 40x40 Galvanis','Besi & Baja','batang'],['BAJ-H20','Hollow 20x40 Galvanis','Besi & Baja','batang'],['BAJ-PLAT','Plat Besi 1.2 mm','Besi & Baja','lembar'],['BAJ-BEND','Bendrat','Besi & Baja','kg'],
  ['DND-BM','Bata Merah','Dinding','buah'],['DND-BR75','Bata Ringan 7.5 cm','Dinding','buah'],['DND-BR10','Bata Ringan 10 cm','Dinding','buah'],['DND-BTK','Batako Press','Dinding','buah'],['DND-GRC4','GRC Board 4 mm','Dinding','lembar'],['DND-GRC6','GRC Board 6 mm','Dinding','lembar'],['DND-GYP9','Gypsum Board 9 mm','Dinding','lembar'],['DND-GYP12','Gypsum Board 12 mm','Dinding','lembar'],
  ['KRM-4040','Keramik 40x40','Keramik & Batu','dus'],['KRM-6060','Keramik 60x60','Keramik & Batu','dus'],['GRT-6060','Granit 60x60','Keramik & Batu','dus'],['GRT-8080','Granit 80x80','Keramik & Batu','dus'],['HTM-001','Homogeneous Tile 60x60','Keramik & Batu','dus'],['BAT-AND','Batu Andesit','Keramik & Batu','m2'],['BAT-PAL','Batu Palimanan','Keramik & Batu','m2'],['KRM-LEM','Tile Adhesive','Keramik & Batu','zak'],['KRM-NAT','Tile Grout / Nat','Keramik & Batu','kg'],
  ['CAT-INT','Cat Interior','Cat & Finishing','pail'],['CAT-EKS','Cat Eksterior','Cat & Finishing','pail'],['CAT-PLM','Plamir Tembok','Cat & Finishing','pail'],['CAT-DAS','Cat Dasar Alkali','Cat & Finishing','pail'],['CAT-BSI','Cat Besi','Cat & Finishing','kaleng'],['CAT-KYU','Cat Kayu','Cat & Finishing','kaleng'],['CAT-THN','Thinner','Cat & Finishing','liter'],['CAT-WP','Waterproofing Coating','Cat & Finishing','pail'],['CAT-EPO','Epoxy Floor','Cat & Finishing','set'],['CAT-SIL','Silicone Sealant','Cat & Finishing','tube'],['CAT-PU','PU Sealant','Cat & Finishing','tube'],
  ['KAY-4/6','Kayu Kaso 4/6','Kayu','batang'],['KAY-5/7','Kayu Kaso 5/7','Kayu','batang'],['KAY-5/10','Kayu Balok 5/10','Kayu','batang'],['KAY-P12','Plywood 12 mm','Kayu','lembar'],['KAY-P15','Plywood 15 mm','Kayu','lembar'],['KAY-P18','Plywood 18 mm','Kayu','lembar'],['KAY-TRP','Triplek 3 mm','Kayu','lembar'],['KAY-MDF','MDF Board 12 mm','Kayu','lembar'],
  ['ATAP-GNT','Genteng Beton','Atap','buah'],['ATAP-MTL','Genteng Metal','Atap','lembar'],['ATAP-SPD','Spandek 0.35 mm','Atap','lembar'],['ATAP-PVC','Atap PVC','Atap','lembar'],['ATAP-POL','Polycarbonate','Atap','lembar'],['ATAP-FOIL','Aluminium Foil Insulation','Atap','roll'],['ATAP-RNG','Rangka Baja Ringan C75','Atap','batang'],['ATAP-RNG2','Reng Baja Ringan','Atap','batang'],
  ['PVC-050','Pipa PVC AW 1/2 inch','Plumbing','batang'],['PVC-075','Pipa PVC AW 3/4 inch','Plumbing','batang'],['PVC-100','Pipa PVC AW 1 inch','Plumbing','batang'],['PVC-150','Pipa PVC AW 1 1/2 inch','Plumbing','batang'],['PVC-200','Pipa PVC AW 2 inch','Plumbing','batang'],['PVC-300','Pipa PVC D 3 inch','Plumbing','batang'],['PVC-400','Pipa PVC D 4 inch','Plumbing','batang'],['PPR-020','Pipa PPR PN20 20 mm','Plumbing','batang'],['PPR-025','Pipa PPR PN20 25 mm','Plumbing','batang'],['PPR-032','Pipa PPR PN20 32 mm','Plumbing','batang'],['PLB-ELB','Elbow PVC/PPR','Plumbing','buah'],['PLB-TEE','Tee PVC/PPR','Plumbing','buah'],['PLB-VAL','Ball Valve','Plumbing','buah'],['PLB-FD','Floor Drain','Plumbing','buah'],['PLB-CLN','Clean Out','Plumbing','buah'],['PLB-WC','Kloset Duduk','Sanitary','unit'],['PLB-WST','Wastafel','Sanitary','unit'],['PLB-SHW','Shower Set','Sanitary','set'],['PLB-KRN','Kran Air','Sanitary','buah'],['PLB-TNK','Tangki Air','Sanitary','unit'],['PLB-PMP','Pompa Air','Sanitary','unit'],
  ['EL-NYA15','Kabel NYA 1.5 mm²','Elektrikal','roll'],['EL-NYA25','Kabel NYA 2.5 mm²','Elektrikal','roll'],['EL-NYM2','Kabel NYM 2x1.5 mm²','Elektrikal','roll'],['EL-NYM3','Kabel NYM 3x2.5 mm²','Elektrikal','roll'],['EL-NYY4','Kabel NYY 4x4 mm²','Elektrikal','meter'],['EL-CON20','Conduit 20 mm','Elektrikal','batang'],['EL-MCB6','MCB 6A','Elektrikal','buah'],['EL-MCB10','MCB 10A','Elektrikal','buah'],['EL-MCB16','MCB 16A','Elektrikal','buah'],['EL-RCCB','RCCB/ELCB','Elektrikal','buah'],['EL-PNL','Panel Listrik','Elektrikal','unit'],['EL-SKL','Saklar','Elektrikal','buah'],['EL-SKT','Stop Kontak','Elektrikal','buah'],['EL-LMP','Lampu LED','Elektrikal','buah'],['EL-BOX','Inbow Box','Elektrikal','buah'],['EL-GND','Ground Rod','Elektrikal','batang'],
  ['DR-PNL','Pintu Panel','Pintu & Jendela','unit'],['DR-ALU','Pintu Aluminium','Pintu & Jendela','unit'],['DR-KYU','Pintu Kayu','Pintu & Jendela','unit'],['WND-ALU','Jendela Aluminium','Pintu & Jendela','unit'],['GLS-5','Kaca 5 mm','Pintu & Jendela','m2'],['GLS-8','Kaca Tempered 8 mm','Pintu & Jendela','m2'],['GLS-10','Kaca Tempered 10 mm','Pintu & Jendela','m2'],['ACC-HNG','Engsel','Pintu & Jendela','buah'],['ACC-LCK','Handle + Lockset','Pintu & Jendela','set'],
  ['FRM-PH','Paku 5 cm','Bekisting & Fastener','kg'],['FRM-PH7','Paku 7 cm','Bekisting & Fastener','kg'],['FRM-PH10','Paku 10 cm','Bekisting & Fastener','kg'],['FRM-SKR','Sekrup Gypsum','Bekisting & Fastener','box'],['FRM-DYN','Dynabolt','Bekisting & Fastener','buah'],['FRM-ANCH','Chemical Anchor','Bekisting & Fastener','tube'],['FRM-TIE','Tie Rod Bekisting','Bekisting & Fastener','set'],['FRM-OIL','Minyak Bekisting','Bekisting & Fastener','liter'],
  ['HSE-HEL','Safety Helmet','HSE','buah'],['HSE-VST','Safety Vest','HSE','buah'],['HSE-SHO','Safety Shoes','HSE','pasang'],['HSE-GLV','Sarung Tangan Kerja','HSE','pasang'],['HSE-MSK','Masker','HSE','box'],['HSE-GLS','Safety Glasses','HSE','buah'],['HSE-HRN','Full Body Harness','HSE','set'],['HSE-APAR','APAR','HSE','unit'],['HSE-TAPE','Safety Line','HSE','roll'],
  ['CNS-DIS','Cutting Disc 4 inch','Consumable','buah'],['CNS-GRD','Grinding Disc 4 inch','Consumable','buah'],['CNS-DRL','Mata Bor Beton','Consumable','buah'],['CNS-WLD','Kawat Las','Consumable','kg'],['CNS-GAS','Gas LPG/Oxygen','Consumable','tabung'],['CNS-GLU','Lem PVC','Consumable','kaleng'],['CNS-TFL','Seal Tape','Consumable','roll'],['CNS-RAF','Rafia','Consumable','roll'],['CNS-TRP','Terpal','Consumable','lembar'],['CNS-SCK','Karung','Consumable','buah'],
  ['LAN-PVG','Paving Block','Landscape','m2'],['LAN-GRS','Rumput Gajah Mini','Landscape','m2'],['LAN-SOI','Top Soil','Landscape','m3'],['LAN-PLN','Tanaman Landscape','Landscape','unit'],['LAN-BRD','Kansteen','Landscape','buah'],
  ['INF-SCF','Scaffolding Set','Peralatan/Sewa','set'],['INF-MIX','Concrete Mixer','Peralatan/Sewa','unit'],['INF-VIB','Concrete Vibrator','Peralatan/Sewa','unit'],['INF-CUT','Bar Cutter','Peralatan/Sewa','unit'],['INF-BEN','Bar Bender','Peralatan/Sewa','unit'],['INF-GRD','Mesin Gerinda','Peralatan/Sewa','unit'],['INF-DRL','Mesin Bor','Peralatan/Sewa','unit'],['INF-WLD','Mesin Las','Peralatan/Sewa','unit'],['INF-GEN','Genset','Peralatan/Sewa','unit'],['INF-STP','Stamper','Peralatan/Sewa','unit'],['INF-EXC','Excavator','Peralatan/Sewa','hari'],['INF-CRN','Mobile Crane','Peralatan/Sewa','hari'],['INF-PMP','Concrete Pump','Peralatan/Sewa','shift'],
  ['MISC-WTR','Air Kerja','Utilitas','m3'],['MISC-ELC','Listrik Kerja','Utilitas','kWh'],['MISC-FUL','Solar/Diesel','Utilitas','liter'],['MISC-TLS','Toolbox Consumable','Utilitas','paket']
].map(([code,name,category,unit])=>({code,name,category,unit,defaultPrice:0,minStock:0,active:true}));

export const WORK_TYPES = [
  'Persiapan','Mobilisasi','Pengukuran/Bouwplank','Pekerjaan Tanah','Pondasi','Struktur Beton','Struktur Baja','Pasangan Dinding','Plester & Acian','Atap','Waterproofing','Plafon','Lantai & Keramik','Pintu & Jendela','Pengecatan','Plumbing','Sanitary','Elektrikal','MEP','Facade','Landscape','Drainase','Paving/Jalan','Pembersihan','Testing & Commissioning','Defect/Punch List','Serah Terima'
];

export const UNITS = ['buah','pcs','unit','set','batang','lembar','roll','box','dus','zak','kg','ton','liter','pail','tabung','meter','m','m2','m3','hari','jam','shift','kWh','paket','orang'];
